version: '3.3'
services:
  todo_ui:
    restart: always
    container_name: todo_ui
    image: todo_ui:latest
    build:
      context: ./client
      dockerfile: ./Dockerfile
    networks:
      - todo
    ports:
      - "80:80"
  todo_api:
    restart: always
    container_name: todo_api
    image: todo_api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    networks:
      - todo
    env_file: 
      - .env
    ports:
      - "3000:3000"

networks:
  todo:
    driver: bridge
